//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kr_loginn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public int id { get; set; }
        public string role { get; set; }
        public Nullable<int> id_login { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
